import { IDataProduct } from "@/models/product";

export const dataProduct: IDataProduct[] = [
  {
    id: "1",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "2",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "3",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "4",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "5",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "6",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "7",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "8",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "9",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "10",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "11",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "12",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "13",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "14",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "15",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "16",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "17",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "18",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "19",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
  {
    id: "20",
    name: "Cake",
    price: 10000,
    image: "https://brunchcafe.com/wp-content/uploads/2020/12/IMG_2127.jpeg",
    totalSold: 10,
  },
];

export const invoices = [
  {
    code: "INV001",
    customer: "Lex",
    totalAmount: 250000,
    paymentMethod: "Cash",
  },
  {
    code: "INV002",
    customer: "Jhon",
    totalAmount: 150000,
    paymentMethod: "Cash",
  },
  {
    code: "INV003",
    customer: "Maxalister",
    totalAmount: 35000,
    paymentMethod: "Qris",
  },
  {
    code: "INV004",
    customer: "Paity",
    totalAmount: 45000,
    paymentMethod: "Cash",
  },
  {
    code: "INV005",
    customer: "Noah",
    totalAmount: 50000,
    paymentMethod: "Qris",
  },
  {
    code: "INV006",
    customer: "Lucas",
    totalAmount: 200000,
    paymentMethod: "Cash",
  },
  {
    code: "INV007",
    customer: "Jhosua",
    totalAmount: 34000,
    paymentMethod: "Qris",
  },
  {
    code: "INV001",
    customer: "Lex",
    totalAmount: 250000,
    paymentMethod: "Cash",
  },
  {
    code: "INV002",
    customer: "Jhon",
    totalAmount: 150000,
    paymentMethod: "Cash",
  },
  {
    code: "INV003",
    customer: "Maxalister",
    totalAmount: 35000,
    paymentMethod: "Qris",
  },
  {
    code: "INV004",
    customer: "Paity",
    totalAmount: 45000,
    paymentMethod: "Cash",
  },
  {
    code: "INV005",
    customer: "Noah",
    totalAmount: 50000,
    paymentMethod: "Qris",
  },
  {
    code: "INV006",
    customer: "Lucas",
    totalAmount: 200000,
    paymentMethod: "Cash",
  },
  {
    code: "INV007",
    customer: "Jhosua",
    totalAmount: 34000,
    paymentMethod: "Qris",
  },
  {
    code: "INV001",
    customer: "Lex",
    totalAmount: 250000,
    paymentMethod: "Cash",
  },
  {
    code: "INV002",
    customer: "Jhon",
    totalAmount: 150000,
    paymentMethod: "Cash",
  },
  {
    code: "INV003",
    customer: "Maxalister",
    totalAmount: 35000,
    paymentMethod: "Qris",
  },
  {
    code: "INV004",
    customer: "Paity",
    totalAmount: 45000,
    paymentMethod: "Cash",
  },
  {
    code: "INV005",
    customer: "Noah",
    totalAmount: 50000,
    paymentMethod: "Qris",
  },
  {
    code: "INV006",
    customer: "Lucas",
    totalAmount: 200000,
    paymentMethod: "Cash",
  },
  {
    code: "INV007",
    customer: "Jhosua",
    totalAmount: 34000,
    paymentMethod: "Qris",
  },
  {
    code: "INV001",
    customer: "Lex",
    totalAmount: 250000,
    paymentMethod: "Cash",
  },
  {
    code: "INV002",
    customer: "Jhon",
    totalAmount: 150000,
    paymentMethod: "Cash",
  },
  {
    code: "INV003",
    customer: "Maxalister",
    totalAmount: 35000,
    paymentMethod: "Qris",
  },
  {
    code: "INV004",
    customer: "Paity",
    totalAmount: 45000,
    paymentMethod: "Cash",
  },
  {
    code: "INV005",
    customer: "Noah",
    totalAmount: 50000,
    paymentMethod: "Qris",
  },
  {
    code: "INV006",
    customer: "Lucas",
    totalAmount: 200000,
    paymentMethod: "Cash",
  },
  {
    code: "INV007",
    customer: "Jhosua",
    totalAmount: 34000,
    paymentMethod: "Qris",
  },
];
